### PR TITLE
added wishlist page only ui

### PR DESCRIPTION
**Pull request by nikhiljugale007**
PR for ui of wishlist page. 
Shows list of products with option to remove from wishlist and add to cart option.

file to check:
wishlist.jsx
wishlist.css
productcard.jsx

### CODE REVIEW

**Review by Sahil25061999 — APPROVED** [review]
code looks good, a suggestion for ui would be to make the close icon a bit big rest of the ui looks great.

**Review by sri-rishi — APPROVED** [review]
Code looks good, just UI Suggestion can give some space between heading and card-section and 
between cards vertically 

image

**Review by thenorthkun — APPROVED** [review]
Code look fine 👍
UI suggestion : You can add a bit of `margin-left` or something to give space on left of the grid container.

**Comment by nikhiljugale007** [comment]
> code looks good, a suggestion for ui would be to make the close icon a bit big rest of the ui looks great.

Made close button larger in new commit.

**Comment by nikhiljugale007** [comment]
> Code look fine 👍 UI suggestion : You can add a bit of `margin-left` or something to give space on left of the grid container.

added margin left in new commit.

**Comment by nikhiljugale007** [comment]
> Code looks good, just UI Suggestion can give some space between heading and card-section and between cards vertically
> 
> image

added more padding around page heading.

**Pull request merged**
